# Generated by Django 5.1.6 on 2025-02-13 04:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tbltib',
            fields=[
                ('fldID', models.AutoField(primary_key=True, serialize=False)),
                ('fldNo', models.CharField(db_index=True, max_length=50)),
                ('fldStatus', models.CharField(max_length=20)),
                ('fldCoordinate', models.CharField(max_length=200)),
                ('fldOrientation', models.CharField(max_length=20)),
                ('fldPicture', models.TextField(blank=True, null=True)),
                ('fldLastMDate', models.DateTimeField(default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(max_length=250)),
            ],
            options={
                'db_table': 'Tbltib',
                'managed': False,
            },
        ),
    ]
