# Generated by Django 5.1.6 on 2025-02-18 09:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_tbltib'),
    ]

    operations = [
        migrations.CreateModel(
            name='Airline',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldStatus', models.CharField(db_column='fldStatus', default='', max_length=20)),
                ('fldCode', models.CharField(db_column='fldCode', default='', max_length=20)),
                ('fldEnglishName', models.CharField(db_column='fldEnglishName', default='', max_length=200)),
                ('fldChineseName', models.CharField(db_column='fldChineseName', default='', max_length=200)),
                ('fldPicture', models.TextField(blank=True, db_column='fldPicture', null=True)),
                ('fldLastMDate', models.DateTimeField(db_column='fldLastMDate', default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(db_column='fldEmpNameM', default='', max_length=250)),
                ('fldWithDesks', models.CharField(db_column='fldWithDesks', default='', max_length=10)),
                ('fldHotline', models.CharField(db_column='fldHotline', default='', max_length=50)),
            ],
            options={
                'db_table': 'tblairline',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AirlineBackup',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldStatus', models.CharField(db_column='fldStatus', default='', max_length=20)),
                ('fldCode', models.CharField(db_column='fldCode', default='', max_length=20)),
                ('fldEnglishName', models.CharField(db_column='fldEnglishName', default='', max_length=200)),
                ('fldChineseName', models.CharField(db_column='fldChineseName', default='', max_length=200)),
                ('fldPicture', models.TextField(blank=True, db_column='fldPicture', null=True)),
                ('fldLastMDate', models.DateTimeField(db_column='fldLastMDate', default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(db_column='fldEmpNameM', default='', max_length=250)),
                ('fldWithDesks', models.CharField(db_column='fldWithDesks', default='', max_length=10)),
                ('fldHotline', models.CharField(db_column='fldHotline', default='', max_length=50)),
            ],
            options={
                'db_table': 'tblairline_backup',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AirlineOpenTime',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldAirlineID', models.IntegerField(db_column='fldAirlineID', default=0)),
                ('fldWeekDays', models.CharField(db_column='fldWeekDays', default='', max_length=50)),
                ('fldTransferDesk', models.CharField(db_column='fldTransferDesk', default='', max_length=200)),
                ('fldStartTime', models.CharField(db_column='fldStartTime', default='', max_length=10)),
                ('fldEndTime', models.CharField(db_column='fldEndTime', default='', max_length=10)),
                ('fldFullTime', models.CharField(db_column='fldFullTime', default='', max_length=10)),
                ('fldLastMDate', models.DateTimeField(db_column='fldLastMDate', default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(db_column='fldEmpNameM', default='', max_length=250)),
            ],
            options={
                'db_table': 'tblairlineopentime',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='AirlineOpenTimeBackup',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldAirlineID', models.IntegerField(db_column='fldAirlineID', default=0)),
                ('fldWeekDays', models.CharField(db_column='fldWeekDays', default='', max_length=50)),
                ('fldTransferDesk', models.CharField(db_column='fldTransferDesk', default='', max_length=200)),
                ('fldStartTime', models.CharField(db_column='fldStartTime', default='', max_length=10)),
                ('fldEndTime', models.CharField(db_column='fldEndTime', default='', max_length=10)),
                ('fldFullTime', models.CharField(db_column='fldFullTime', default='', max_length=10)),
                ('fldLastMDate', models.DateTimeField(db_column='fldLastMDate', default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(db_column='fldEmpNameM', default='', max_length=250)),
            ],
            options={
                'db_table': 'tblairlineopentime',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiChoice',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('choice_text', models.CharField(max_length=200)),
                ('votes', models.IntegerField()),
            ],
            options={
                'db_table': 'api_choice',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='ApiQuestion',
            fields=[
                ('id', models.BigAutoField(primary_key=True, serialize=False)),
                ('question_text', models.CharField(max_length=200)),
                ('pub_date', models.DateTimeField()),
            ],
            options={
                'db_table': 'api_question',
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardingGate',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldNo', models.CharField(db_column='fldNo', default='', max_length=50)),
                ('fldLeftCoordinate', models.CharField(db_column='fldLeftCoordinate', default='', max_length=200)),
                ('fldRightCoordinate', models.CharField(db_column='fldRightCoordinate', default='', max_length=200)),
                ('fldLastMDate', models.DateTimeField(db_column='fldLastMDate', default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(db_column='fldEmpNameM', default='', max_length=250)),
            ],
            options={
                'db_table': 'tblboardinggate',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='BoardingGateBackup',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldNo', models.CharField(db_column='fldNo', default='', max_length=50)),
                ('fldLeftCoordinate', models.CharField(db_column='fldLeftCoordinate', default='', max_length=200)),
                ('fldRightCoordinate', models.CharField(db_column='fldRightCoordinate', default='', max_length=200)),
                ('fldLastMDate', models.DateTimeField(db_column='fldLastMDate', default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(db_column='fldEmpNameM', default='', max_length=250)),
            ],
            options={
                'db_table': 'tblboardinggate_backup',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='General',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldName', models.CharField(db_column='fldName', default='', max_length=200)),
                ('fldType', models.CharField(db_column='fldType', default='', max_length=200)),
                ('fldValue', models.TextField(blank=True, db_column='fldValue', null=True)),
                ('fldLastMDate', models.DateTimeField(db_column='fldLastMDate', default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(db_column='fldEmpNameM', default='', max_length=250)),
            ],
            options={
                'db_table': 'tblgeneral',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Tib',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldNo', models.CharField(db_column='fldNo', default='', max_length=50)),
                ('fldStatus', models.CharField(db_column='fldStatus', default='', max_length=20)),
                ('fldOrientation', models.CharField(db_column='fldOrientation', default='', max_length=20)),
                ('fldCoordinate', models.CharField(db_column='fldCoordinate', default='', max_length=200)),
                ('fldPicture', models.TextField(blank=True, db_column='fldPicture', null=True)),
                ('fldLastMDate', models.DateTimeField(db_column='fldLastMDate', default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(db_column='fldEmpNameM', default='', max_length=250)),
            ],
            options={
                'db_table': 'tbltib',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TibBackup',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldNo', models.CharField(db_column='fldNo', default='', max_length=50)),
                ('fldStatus', models.CharField(db_column='fldStatus', default='', max_length=20)),
                ('fldOrientation', models.CharField(db_column='fldOrientation', default='', max_length=20)),
                ('fldCoordinate', models.CharField(db_column='fldCoordinate', default='', max_length=200)),
                ('fldPicture', models.TextField(blank=True, db_column='fldPicture', null=True)),
                ('fldLastMDate', models.DateTimeField(db_column='fldLastMDate', default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(db_column='fldEmpNameM', default='', max_length=250)),
            ],
            options={
                'db_table': 'tbltib_backup',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TibEstimationTime',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldTIBNo', models.CharField(db_column='fldTIBNo', default='', max_length=50)),
                ('fldTransferNo', models.CharField(db_column='fldTransferNo', default='', max_length=50)),
                ('fldTimeWithAPM', models.IntegerField(blank=True, db_column='fldTimeWithAPM', null=True)),
                ('fldDirectionWithAPM', models.CharField(db_column='fldDirectionWithAPM', default='', max_length=1)),
                ('fldTimeWithoutAPM', models.IntegerField(blank=True, db_column='fldTimeWithoutAPM', null=True)),
                ('fldDirectionWithoutAPM', models.CharField(db_column='fldDirectionWithoutAPM', default='', max_length=1)),
                ('fldLastMDate', models.DateTimeField(db_column='fldLastMDate', default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(db_column='fldEmpNameM', default='', max_length=250)),
            ],
            options={
                'db_table': 'tbltibestimationtime',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TibEstimationTimeBackup',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldTIBNo', models.CharField(db_column='fldTIBNo', default='', max_length=50)),
                ('fldTransferNo', models.CharField(db_column='fldTransferNo', default='', max_length=50)),
                ('fldTimeWithAPM', models.IntegerField(blank=True, db_column='fldTimeWithAPM', null=True)),
                ('fldDirectionWithAPM', models.CharField(db_column='fldDirectionWithAPM', default='', max_length=1)),
                ('fldTimeWithoutAPM', models.IntegerField(blank=True, db_column='fldTimeWithoutAPM', null=True)),
                ('fldDirectionWithoutAPM', models.CharField(db_column='fldDirectionWithoutAPM', default='', max_length=1)),
                ('fldLastMDate', models.DateTimeField(db_column='fldLastMDate', default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(db_column='fldEmpNameM', default='', max_length=250)),
            ],
            options={
                'db_table': 'tbltibestimationtime',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TibStatus',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldNo', models.CharField(db_column='fldNo', default='', max_length=50)),
                ('fldStatus', models.CharField(db_column='fldStatus', default='', max_length=20)),
                ('fldSendEmail', models.CharField(db_column='fldSendEmail', default='', max_length=5)),
                ('fldLastLoginTime', models.CharField(db_column='fldLastLoginTime', default='', max_length=50)),
            ],
            options={
                'db_table': 'tbltibstatus',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='Transfer',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldType', models.CharField(db_column='fldType', default='', max_length=20)),
                ('fldNo', models.CharField(db_column='fldNo', default='', max_length=50)),
                ('fldStatus', models.CharField(db_column='fldStatus', default='', max_length=20)),
                ('fldName', models.CharField(db_column='fldName', default='', max_length=200)),
                ('fldLeftCoordinate', models.CharField(db_column='fldLeftCoordinate', default='', max_length=200)),
                ('fldRightCoordinate', models.CharField(db_column='fldRightCoordinate', default='', max_length=200)),
                ('fldLeftPicture', models.TextField(blank=True, db_column='fldLeftPicture', null=True)),
                ('fldRightPicture', models.TextField(blank=True, db_column='fldRightPicture', null=True)),
                ('fldStartTime', models.CharField(db_column='fldStartTime', default='', max_length=10)),
                ('fldEndTime', models.CharField(db_column='fldEndTime', default='', max_length=10)),
                ('fldFullTime', models.CharField(db_column='fldFullTime', default='', max_length=10)),
                ('fldLastMDate', models.DateTimeField(db_column='fldLastMDate', default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(db_column='fldEmpNameM', default='', max_length=250)),
            ],
            options={
                'db_table': 'tbltransfer',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.CreateModel(
            name='TransferBackup',
            fields=[
                ('fldID', models.AutoField(db_column='fldID', primary_key=True, serialize=False)),
                ('fldType', models.CharField(db_column='fldType', default='', max_length=20)),
                ('fldNo', models.CharField(db_column='fldNo', default='', max_length=50)),
                ('fldStatus', models.CharField(db_column='fldStatus', default='', max_length=20)),
                ('fldName', models.CharField(db_column='fldName', default='', max_length=200)),
                ('fldLeftCoordinate', models.CharField(db_column='fldLeftCoordinate', default='', max_length=200)),
                ('fldRightCoordinate', models.CharField(db_column='fldRightCoordinate', default='', max_length=200)),
                ('fldLeftPicture', models.TextField(blank=True, db_column='fldLeftPicture', null=True)),
                ('fldRightPicture', models.TextField(blank=True, db_column='fldRightPicture', null=True)),
                ('fldStartTime', models.CharField(db_column='fldStartTime', default='', max_length=10)),
                ('fldEndTime', models.CharField(db_column='fldEndTime', default='', max_length=10)),
                ('fldFullTime', models.CharField(db_column='fldFullTime', default='', max_length=10)),
                ('fldLastMDate', models.DateTimeField(db_column='fldLastMDate', default='0001-01-01 00:00:00')),
                ('fldEmpNameM', models.CharField(db_column='fldEmpNameM', default='', max_length=250)),
            ],
            options={
                'db_table': 'tbltransfer_backup',
                'ordering': ['fldID'],
                'managed': False,
            },
        ),
        migrations.RemoveField(
            model_name='choice',
            name='question',
        ),
        migrations.DeleteModel(
            name='Tbltib',
        ),
        migrations.DeleteModel(
            name='Choice',
        ),
        migrations.DeleteModel(
            name='Question',
        ),
    ]
